send_alert:
  name: Send Alert
  description: Sends a custom alert notification
  fields:
    message:
      name: Message
      description: The message content to display in the notification.
      required: true
      example: "Inverter is disconnected!"
      selector:
        text:
    title:
      name: Title
      description: The title of the notification.
      required: false
      default: "Solar Plus Intelbras Alert"
      example: "Inverter Status"
      selector:
        text:
    notification_id:
      name: Notification ID
      description: A unique ID for the notification. If not provided, a unique ID will be generated.
      required: false
      example: "solar_inverter_status"
      selector:
        text:
    priority:
      name: Priority
      description: The priority level of the notification.
      required: false
      default: "normal"
      selector:
        select:
          options:
            - "normal"
            - "warning"
            - "critical"
            - "info"
