name: "Release"

on:
  release:
    types:
      - "published"

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4.2.2"

      - name: "ZIP the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}"
          zip -r solar_plus_intelbras.zip custom_components/solar_plus_intelbras/

      - name: "Upload the ZIP file to the release"
        uses: "softprops/action-gh-release@v2.2.0"
        with:
          files: ${{ github.workspace }}/solar_plus_intelbras.zip
